language: scala

scala:
  - 2.12.8

jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.sbt/1.0/dependency
    - $HOME/.sbt/launchers
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete

before_install:
 - export PATH=${PATH}:./vendor/bundle

install:
  - rvm use 2.6.0 --install --fuzzy
  - gem update --system
  - gem install sass
  - gem install jekyll -v 3.8.5

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport docs/makeMicrosite

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
      if [ "$SBT_VERSION" = "1.2.8" ]; then
        git reset --hard HEAD;
        git clean -f;
        git checkout master;
        git pull origin master;
        sbt ^^$SBT_VERSION docs/publishMicrosite;
      fi
    fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d54a74117bc77b928e1f
    on_success: change
    on_failure: always
    on_start: never