name: ScalaRL
baseurl: ''
description: Reinforcement Learning in Scala.
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 0.1.0-SNAPSHOT
org: io.samritchie
markdown: kramdown
